### ISSUE TITLE
Next window shortcut bug with app/popup windows

### ISSUE THREAD

**Issue by dmitry-hohlov** [acarabott/tabToWindow#43]
I use Windows 10 with all updates (version 1803, build 17134.345) and latest version of Chrome (70.0.3538.77).

When I have Chrome application/popup window opened among other normal Chrome windows and on some tab I press "window" shortcut and then "next window" shortcut several times it will move this tab among normal windows until it hit the app/popup window. At this point app/popup window will get the focus as if TabToWindow tried to move my tab to this app/popup window. Of course the tab is not moved there because there is no tabs in this window. But now this app/popup window has the focus. And if I press "next window" shortcut again this app/popup becomes a tab and moves to new window.

All this looks like a bug. I think TabToWindow should not try to move tabs to app/popup windows.

**Comment by acarabott** [comment]
Thanks for finding this @dmitry-hohlov . I will have time to fix this in December.

Cheers,

Arthur

**Comment by misterpyrrhuloxia** [comment]
I experience this every single day as well. I've had to try to work around it by opening my multiple different Chrome windows in a different order than I like. The reason I like to open my Chrome windows in a particular order is so that links opened from applications outside of Chrome always open in my preferred Chrome window. But because I have to open up my three Chrome windows in a different order than I prefer, I don't get the benefit of externally-opened links opening in my preferred Chrome window.

**Comment by acarabott** [comment]
This is now fixed, will be available in version `3.2.0`, which is pending approval from Google.

Apologies it took so long to fix, I moved country.
